//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratuvars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laboratuvars()
        {
            this.Map_BilgisayarLaboratuvar = new HashSet<Map_BilgisayarLaboratuvar>();
        }
    
        public int id { get; set; }
        public string adi { get; set; }
        public int KurulusYili { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Map_BilgisayarLaboratuvar> Map_BilgisayarLaboratuvar { get; set; }
    }
}
