//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map_BilgisayarLaboratuvar
    {
        public int id { get; set; }
        public Nullable<int> bilgisayar_id_id { get; set; }
        public Nullable<int> laboratuvar_id_id { get; set; }
    
        public virtual Bilgisayars Bilgisayars { get; set; }
        public virtual Laboratuvars Laboratuvars { get; set; }
    }
}
