//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoExample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LABSEntities : DbContext
    {
        public LABSEntities()
            : base("name=LABSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Bilgisayars> Bilgisayars { get; set; }
        public virtual DbSet<Laboratuvars> Laboratuvars { get; set; }
        public virtual DbSet<Map_BilgisayarLaboratuvar> Map_BilgisayarLaboratuvar { get; set; }
    }
}
